/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedReportIndexRouteImport } from './routes/_authenticated/report.index'
import { Route as ApiPublicIngestEventsRouteImport } from './routes/api/public/ingest-events'
import { Route as ApiPublicExpireEventsRouteImport } from './routes/api/public/expire-events'
import { Route as ApiPublicCheckFeedsRouteImport } from './routes/api/public/check-feeds'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportIndexRoute =
  AuthenticatedReportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportRoute,
  } as any)
const ApiPublicIngestEventsRoute = ApiPublicIngestEventsRouteImport.update({
  id: '/api/public/ingest-events',
  path: '/api/public/ingest-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpireEventsRoute = ApiPublicExpireEventsRouteImport.update({
  id: '/api/public/expire-events',
  path: '/api/public/expire-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckFeedsRoute = ApiPublicCheckFeedsRouteImport.update({
  id: '/api/public/check-feeds',
  path: '/api/public/check-feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/api/public/check-feeds': typeof ApiPublicCheckFeedsRoute
  '/api/public/expire-events': typeof ApiPublicExpireEventsRoute
  '/api/public/ingest-events': typeof ApiPublicIngestEventsRoute
  '/report/': typeof AuthenticatedReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/api/public/check-feeds': typeof ApiPublicCheckFeedsRoute
  '/api/public/expire-events': typeof ApiPublicExpireEventsRoute
  '/api/public/ingest-events': typeof ApiPublicIngestEventsRoute
  '/report': typeof AuthenticatedReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/api/public/check-feeds': typeof ApiPublicCheckFeedsRoute
  '/api/public/expire-events': typeof ApiPublicExpireEventsRoute
  '/api/public/ingest-events': typeof ApiPublicIngestEventsRoute
  '/_authenticated/report/': typeof AuthenticatedReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/feed'
    | '/map'
    | '/profile'
    | '/report'
    | '/api/chat'
    | '/report/$id'
    | '/api/public/check-feeds'
    | '/api/public/expire-events'
    | '/api/public/ingest-events'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistant'
    | '/feed'
    | '/map'
    | '/profile'
    | '/api/chat'
    | '/report/$id'
    | '/api/public/check-feeds'
    | '/api/public/expire-events'
    | '/api/public/ingest-events'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/feed'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/api/chat'
    | '/_authenticated/report/$id'
    | '/api/public/check-feeds'
    | '/api/public/expire-events'
    | '/api/public/ingest-events'
    | '/_authenticated/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicCheckFeedsRoute: typeof ApiPublicCheckFeedsRoute
  ApiPublicExpireEventsRoute: typeof ApiPublicExpireEventsRoute
  ApiPublicIngestEventsRoute: typeof ApiPublicIngestEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/': {
      id: '/_authenticated/report/'
      path: '/'
      fullPath: '/report/'
      preLoaderRoute: typeof AuthenticatedReportIndexRouteImport
      parentRoute: typeof AuthenticatedReportRoute
    }
    '/api/public/ingest-events': {
      id: '/api/public/ingest-events'
      path: '/api/public/ingest-events'
      fullPath: '/api/public/ingest-events'
      preLoaderRoute: typeof ApiPublicIngestEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-events': {
      id: '/api/public/expire-events'
      path: '/api/public/expire-events'
      fullPath: '/api/public/expire-events'
      preLoaderRoute: typeof ApiPublicExpireEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-feeds': {
      id: '/api/public/check-feeds'
      path: '/api/public/check-feeds'
      fullPath: '/api/public/check-feeds'
      preLoaderRoute: typeof ApiPublicCheckFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedReportRoute
    }
  }
}

interface AuthenticatedReportRouteChildren {
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
  AuthenticatedReportIndexRoute: typeof AuthenticatedReportIndexRoute
}

const AuthenticatedReportRouteChildren: AuthenticatedReportRouteChildren = {
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
  AuthenticatedReportIndexRoute: AuthenticatedReportIndexRoute,
}

const AuthenticatedReportRouteWithChildren =
  AuthenticatedReportRoute._addFileChildren(AuthenticatedReportRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicCheckFeedsRoute: ApiPublicCheckFeedsRoute,
  ApiPublicExpireEventsRoute: ApiPublicExpireEventsRoute,
  ApiPublicIngestEventsRoute: ApiPublicIngestEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
